export const BASEUSER_INFO_LOAD = 'BASEUSER_INFO_LOAD';
export const BASEUSER_INFO_LOADED = 'BASEUSER_INFO_LOADED';
export const BASES_LOADED = 'BASES_LOADED';

export const BASE_INFO_LOADED = 'BASE_INFO_LOADED';
export const ROOMS_LOADED = 'ROOMS_LOADED';

export const ROOM_INFO_LOADED = 'ROOM_INFO_LOADED';
